export const TYPES = {
  AUTH_SERVICE: Symbol.for("AuthService"),
  AUTH_REPOSITORY: Symbol.for("AuthRepository"),
  SIGN_IN_WITH_APPLE_USE_CASE: Symbol.for("SignInWithAppleUseCase"),
  SIGN_IN_WITH_GOOGLE_USE_CASE: Symbol.for("SignInWithGoogleUseCase"),
  SEND_OTP_USE_CASE: Symbol.for("SendOtpUseCase"),
  VERIFY_OTP_USE_CASE: Symbol.for("VerifyOtpUseCase"),
  VERIFY_TOKEN_USE_CASE: Symbol.for("VerifyTokenUseCase"),
  TOKEN_SERVICE: Symbol.for("TokenService"),
  REFRESH_TOKEN_USE_CASE: Symbol.for("RefreshTokenUseCase"),
  DASHBOARD_REPOSITORY: Symbol.for("DashboardRepository"),
  GET_CURRENT_USER_USE_CASE: Symbol.for("GetCurrentUserUseCase"),
  GET_WORKOUT_TEMPLATES_USE_CASE: Symbol.for("GetWorkoutTemplatesUseCase"),
  SYNC_REPOSITORY: Symbol.for("SyncRepository"),
  SYNC_WORKOUT_TEMPLATES_USE_CASE: Symbol.for("SyncWorkoutTemplatesUseCase"),
  CHECK_USER_DEVICE_USE_CASE: Symbol.for("CheckUserDeviceUseCase"),
  GET_NON_SYNC_DATA_USE_CASE: Symbol.for("GetNonSyncDataUseCase"),
  SYNC_CLIENT_DATA_USE_CASE: Symbol.for("SyncClientDataUseCase"),
  SYNC_SUB_SERVICE: Symbol.for("SyncSubService"),
};
